### ISSUE TITLE
Quick suggestions

### ISSUE THREAD

**Issue by transitive-bullshit** [dqbd/tiktokenizer#1]
Love this project, David 💯 

A few low-hanging suggestions to improve the repo:

1. Add a desc to the github repo's metadata (in the upper right corner; same place you edit the URL metadata for the repo). This is really helpful because it's what shows up in opengraph metadata and when shared around the github site itself.
2. Add a screenshot to the readme like in your tweet 😄
3. Add a license file; just copy one from an existing repo

You'd be amazed at how much these small details impact developer conversions, especially the image.

Keep up the great work && thanks 🙏

**Comment by dqbd** [comment]
Thank you for the suggestions 😄
