### ISSUE TITLE
changing tokenizer resets the textarea

### ISSUE THREAD

**Issue by opyate** [dqbd/tiktokenizer#19]
Changing tokenizer resets the textarea. I just lost my example! :)

Steps to reproduce:

Go to https://tiktokenizer.vercel.app/

Enter anything into user content input box:

![image](https://github.com/dqbd/tiktokenizer/assets/96808/d789d35c-1848-4fa3-b95a-15d64728ab5a)

Now change the tokenizer from the dropdown box to e.g. gpt2:

![image](https://github.com/dqbd/tiktokenizer/assets/96808/a5da450b-057c-445b-ac27-8a5b7534b12c)

...and the example gets reset:

![image](https://github.com/dqbd/tiktokenizer/assets/96808/2d81b09e-d44c-48ea-9c3b-627fa87ac580)

**Comment by dqbd** [comment]
Hello! That's by design, as you're switching from ChatML playground to a string playground. Will make a note to better distinguish those though!
