### ISSUE TITLE
TokenViewer shows "replacement characters" when entering CJK characters

### ISSUE THREAD

**Issue by firede** [dqbd/tiktokenizer#2]
👍🏻 The project is awesome!

Just a heads up: when inputting Chinese, Japanese, or Korean characters in Tiktokenizer, the TokenViewer displays "replacement characters" (`�`).

<img width="1111" alt="CleanShot 2023-03-16 at 16 42 01@2x" src="https://user-images.githubusercontent.com/157338/225566109-fbee3131-d78d-4c71-9e8d-528191c46cc2.png">

**Comment by dqbd** [comment]
Hi @firede

Thanks for reporting! This should be hopefully fixed now.
