### ISSUE TITLE
Tweak Request: Don't clear prompt textbox when switching models. 

### ISSUE THREAD

**Issue by JonathanFly** [dqbd/tiktokenizer#6]
9 times out of 10, if I'm switching to a new model, it's specifically to compare and visualize prompt sizes _between_ different encoders and models, on the same prompt. Just a little tweak that would personally save me about 100 copy and pastes every day.

**Comment by dqbd** [comment]
Hello @JonathanFly!

Sorry for the long delay. Currently, the prompt textbox is only cleared when switching from a chat model to an autocomplete model (eg. `gpt-3.5-turbo` to `cl100k_base`), which I believe does make sense? 

If I undestand the issue correctly, you are comparing the ChatML prompt messages between different encoders?

**Comment by PeterDaveHello** [comment]
@dqbd looks different to me, the textbox is always cleared no matter which model I switched, even from gpt-4 to gpt-3.5-turbo
